-- VBS De Frères Database Schema

-- Page Content Table
CREATE TABLE IF NOT EXISTS page_content (
    id SERIAL PRIMARY KEY,
    page_slug VARCHAR(100) NOT NULL,
    content_key VARCHAR(100) NOT NULL,
    content_value TEXT,
    content_type VARCHAR(50) DEFAULT 'text',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(page_slug, content_key)
);

-- Enrollments Table
CREATE TABLE IF NOT EXISTS enrollments (
    id SERIAL PRIMARY KEY,
    parent_first_name VARCHAR(100) NOT NULL,
    parent_last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    child_first_name VARCHAR(100) NOT NULL,
    child_last_name VARCHAR(100) NOT NULL,
    child_birthdate DATE NOT NULL,
    start_year VARCHAR(20) NOT NULL,
    message TEXT,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contact Messages Table
CREATE TABLE IF NOT EXISTS contact_messages (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    message TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'unread',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PDF Files Table (stored directly in database, served via /api/pdf/:slug)
CREATE TABLE IF NOT EXISTS pdf_files (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    filename VARCHAR(255) NOT NULL,
    data BYTEA NOT NULL,
    mime_type VARCHAR(100) DEFAULT 'application/pdf',
    size_bytes INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Media Library Table
CREATE TABLE IF NOT EXISTS media (
    id SERIAL PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    public_id VARCHAR(255),
    width INTEGER,
    height INTEGER,
    format VARCHAR(50),
    size_bytes INTEGER,
    alt_text VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Team Members Table
CREATE TABLE IF NOT EXISTS team_members (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(50),
    image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================
-- HOME PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('home', 'hero-title', 'Basisschool De Frères Brugge', 'text'),
('home', 'hero-text', 'Een warme school waar elk kind centraal staat. Samen ontdekken, leren en groeien met een glimlach.', 'text'),
('home', 'hero-bg', '', 'image'),
('home', 'form-title', 'Info en Inschrijven', 'text'),
('home', 'form-subtitle', 'Kom langs voor een warme rondleiding', 'text'),
('home', 'visie-img', '', 'image'),
('home', 'visie-title', 'Waar wij voor staan', 'text'),
('home', 'visie-text', 'Een school met een duidelijk leerklimaat en doelen. We streven naar kwaliteit, aandacht voor individuele noden, en een sterke kennisbasis. Met kleine klassen en een holistische aanpak ontwikkelen we hoofd, hart en handen van elk kind.', 'text'),
('home', 'gallery-1', '', 'image'),
('home', 'gallery-2', '', 'image'),
('home', 'gallery-3', '', 'image'),
('home', 'gallery-4', '', 'image'),
('home', 'gallery-5', '', 'image'),
('home', 'gallery-6', '', 'image'),
('home', 'gallery-7', '', 'image'),
('home', 'gallery-8', '', 'image'),
('home', 'gallery-9', '', 'image'),
('home', 'gallery-10', '', 'image'),
('home', 'cta-title', 'Klaar om deel uit te maken van onze school?', 'text'),
('home', 'cta-text', 'Schrijf je kind in of kom langs voor een rondleiding.', 'text'),
('home', 'contact-director-name', 'Inge Versavel', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- CONTACT PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('contact', 'hero-title', 'Laat ons kennismaken', 'text'),
('contact', 'hero-subtitle', 'Teken hoe graag jij onze school wil bezoeken', 'text'),
('contact', 'email', 'info@vbsdefreres.be', 'text'),
('contact', 'director-photo', '', 'image'),
('contact', 'director-name', 'Inge Versavel', 'text'),
('contact', 'form-title', 'Contactformulier', 'text'),
('contact', 'form-subtitle', 'Vul onderstaand formulier in en we nemen zo snel mogelijk contact met je op', 'text'),
('contact', 'hours-title', 'Bereikbaarheid', 'text'),
('contact', 'school-hours', 'Maandag - Vrijdag: 8:30 - 15:30', 'text'),
('contact', 'office-hours', 'Maandag - Vrijdag: 8:00 - 16:00', 'text'),
('contact', 'care-hours', 'Maandag - Vrijdag: 7:00 - 18:00', 'text'),
('contact', 'location-title', 'Vind ons hier', 'text'),
('contact', 'map-embed', '', 'text'),
('contact', 'cta-title', 'Kom langs voor een bezoek!', 'text'),
('contact', 'cta-text', 'Ontdek onze school en ontmoet ons team tijdens een rondleiding.', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- VISIE PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('visie', 'hero-title', 'Samen bouwen aan een sterke toekomst', 'text'),
('visie', 'hero-text', 'Bij VBS De Frères geloven we in onderwijs dat verder gaat dan kennis alleen. We vormen kinderen tot zelfstandige, creatieve en sociale mensen.', 'text'),
('visie', 'hero-bg', '', 'image'),
('visie', 'mission-title', 'Elk kind verdient de kans om te groeien en te bloeien', 'text'),
('visie', 'mission-text', 'Wij bieden een veilige en stimulerende leeromgeving waar kinderen zich kunnen ontwikkelen op hun eigen tempo. Met aandacht voor individuele talenten en noden, bereiden we hen voor op een succesvolle toekomst.', 'text'),
('visie', 'mission-img', '', 'image'),
('visie', 'sfeer-img-1', '', 'image'),
('visie', 'sfeer-img-2', '', 'image'),
('visie', 'approach-img', '', 'image'),
('visie', 'approach-1-title', 'Eigentijds Onderwijs', 'text'),
('visie', 'approach-1-text', 'We gebruiken moderne lesmethodes en technologie om kinderen optimaal voor te bereiden op de toekomst.', 'text'),
('visie', 'approach-2-title', 'Persoonlijke Begeleiding', 'text'),
('visie', 'approach-2-text', 'Elk kind krijgt de aandacht die het nodig heeft.', 'text'),
('visie', 'approach-3-title', 'Open Communicatie', 'text'),
('visie', 'approach-3-text', 'Transparantie en regelmatig contact met ouders.', 'text'),
('visie', 'doc-1-title', 'Huishoudelijk Reglement', 'text'),
('visie', 'doc-1-desc', 'Basisonderwijs 2024-2025', 'text'),
('visie', 'doc-1-link', '', 'text'),
('visie', 'doc-2-title', 'Infobrochure', 'text'),
('visie', 'doc-2-desc', 'Onderwijsregelgeving', 'text'),
('visie', 'doc-2-link', '', 'text'),
('visie', 'doc-3-title', 'Privacyverklaring', 'text'),
('visie', 'doc-3-desc', 'GDPR & Privacy', 'text'),
('visie', 'doc-3-link', '', 'text'),
('visie', 'doc-4-title', 'Schoolreglement', 'text'),
('visie', 'doc-4-desc', 'Schooljaar 2025-2026', 'text'),
('visie', 'doc-4-link', '', 'text'),
('visie', 'doc-5-title', 'Restaurantmenu', 'text'),
('visie', 'doc-5-desc', 'Week Februari 2025', 'text'),
('visie', 'doc-5-link', '', 'text'),
('visie', 'reglement-pdf', '', 'text'),
('visie', 'cta-title', 'Klaar om deel uit te maken van onze school?', 'text'),
('visie', 'cta-text', 'Kom kennismaken tijdens een rondleiding.', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- KLASSEN PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('klassen', 'hero-title', 'Van kleuter tot middelbaar', 'text'),
('klassen', 'hero-text', 'Ontdek ons volledige onderwijsaanbod. Een doorlopende leerlijn van 2,5 tot 18 jaar op onze groene campus.', 'text'),
('klassen', 'card1-title', 'Kleuter', 'text'),
('klassen', 'card1-subtitle', '2,5 tot 6 jaar', 'text'),
('klassen', 'card1-img', '', 'image'),
('klassen', 'card1-link', '#klasblogs', 'text'),
('klassen', 'card1-linktext', 'Ontdekken', 'text'),
('klassen', 'card2-title', 'Lager', 'text'),
('klassen', 'card2-subtitle', '6 tot 12 jaar', 'text'),
('klassen', 'card2-img', '', 'image'),
('klassen', 'card2-link', '#klasblogs', 'text'),
('klassen', 'card2-linktext', 'Ontdekken', 'text'),
('klassen', 'card3-title', 'Middelbaar', 'text'),
('klassen', 'card3-subtitle', '12 tot 18 jaar', 'text'),
('klassen', 'card3-img', '', 'image'),
('klassen', 'card3-link', 'https://sfxbrugge.be/', 'text'),
('klassen', 'card3-linktext', 'Naar website', 'text'),
('klassen', 'kleuter-title', 'Kleuterklas', 'text'),
('klassen', 'kleuter-subtitle', 'Spelen, ontdekken en groeien in een veilige omgeving', 'text'),
('klassen', 'kleuter-photo', '', 'image'),
('klassen', 'kleuter-1-text', 'Voor de allerkleinsten. Wennen aan school, spelen en sociale vaardigheden ontwikkelen.', 'text'),
('klassen', 'kleuter-2-text', 'Meer structuur en eerste kennismaking met letters, cijfers en creatieve activiteiten.', 'text'),
('klassen', 'kleuter-3-text', 'Voorbereiding op het eerste leerjaar met focus op zelfstandigheid en schoolse vaardigheden.', 'text'),
('klassen', 'lager-title', 'Lagere School', 'text'),
('klassen', 'lager-subtitle', 'Zes jaar vol groei, kennis en nieuwe uitdagingen', 'text'),
('klassen', 'extra-title', 'Meer dan alleen lessen', 'text'),
('klassen', 'extra-text', 'Naast de reguliere lessen bieden we uitstappen, projectweken, sportdagen en culturele activiteiten. Zo maken we leren een avontuur waar kinderen met plezier aan deelnemen.', 'text'),
('klassen', '1-item-1', 'Lezen en schrijven', 'text'),
('klassen', '1-item-2', 'Rekenen tot 100', 'text'),
('klassen', '1-item-3', 'Wereldorientatie', 'text'),
('klassen', '2-item-1', 'Vlot lezen', 'text'),
('klassen', '2-item-2', 'Tafels van vermenigvuldiging', 'text'),
('klassen', '2-item-3', 'Creatieve projecten', 'text'),
('klassen', '3-item-1', 'Begrijpend lezen', 'text'),
('klassen', '3-item-2', 'Breuken en metingen', 'text'),
('klassen', '3-item-3', 'Geschiedenis en aardrijkskunde', 'text'),
('klassen', '4-item-1', 'Complexere teksten', 'text'),
('klassen', '4-item-2', 'Delingen en kommagetallen', 'text'),
('klassen', '4-item-3', 'Wetenschappelijk denken', 'text'),
('klassen', '5-item-1', 'Kritisch lezen en schrijven', 'text'),
('klassen', '5-item-2', 'Verhoudingen en procenten', 'text'),
('klassen', '5-item-3', 'Zelfstandig werken', 'text'),
('klassen', '6-item-1', 'Voorbereiding secundair', 'text'),
('klassen', '6-item-2', 'Complexe vraagstukken', 'text'),
('klassen', '6-item-3', 'Studievaardigheden', 'text'),
('klassen', 'cta-title', 'Interesse in onze school?', 'text'),
('klassen', 'cta-text', 'Neem contact op voor meer informatie of om uw kind in te schrijven.', 'text'),
('klassen', 'peuterklas-text', 'Welkom in onze peuterklas! Hier maken de allerkleinsten (2.5 - 3 jaar) hun eerste stapjes in de schoolwereld. Met veel aandacht, spel en ontdekking groeien ze in een warme, veilige omgeving.', 'text'),
('klassen', 'peuterklas-photo', '', 'image'),
('klassen', 'peuterklas-teacher-photo', '', 'image'),
('klassen', 'peuterklas-teacher-name', 'Juf [Naam]', 'text'),
('klassen', 'k1-text', 'In kleuterklas 1 maken de kinderen kennis met de schoolwereld. Spelen, ontdekken en samen leren staan centraal. Juf Nele begeleidt hen met veel geduld en warmte.', 'text'),
('klassen', 'k1-photo', '', 'image'),
('klassen', 'k1-teacher-photo', '', 'image'),
('klassen', 'k2-text', 'In kleuterklas 2 gaan we verder met ontdekken en leren. De kinderen worden steeds zelfstandiger en maken kennis met letters en cijfers.', 'text'),
('klassen', 'k2-photo', '', 'image'),
('klassen', 'k2-teacher-photo', '', 'image'),
('klassen', 'k3-text', 'De topperklas! Hier bereiden we de kinderen voor op het eerste leerjaar. Zelfstandigheid, schoolse vaardigheden en samenwerken staan centraal.', 'text'),
('klassen', 'k3-photo', '', 'image'),
('klassen', 'k3-teacher-photo', '', 'image'),
('klassen', 'klas-peuterklas-name', 'Peuterklas', 'text'),
('klassen', 'klas-peuterklas-teacher', 'Juf [Naam]', 'text'),
('klassen', 'klas-peuterklas-text', 'Welkom in onze peuterklas! Hier maken de allerkleinsten (2.5 - 3 jaar) hun eerste stapjes in de schoolwereld. Met veel aandacht, spel en ontdekking groeien ze in een warme, veilige omgeving.', 'text'),
('klassen', 'klas-peuterklas-photo', '', 'image'),
('klassen', 'klas-peuterklas-tphoto', '', 'image'),
('klassen', 'klas-peuterklas-blog', '/nl/klas-k1-2', 'text'),
('klassen', 'klas-peuterklas-order', '-4', 'text'),
('klassen', 'klas-k1-name', 'Kleuterklas 1', 'text'),
('klassen', 'klas-k1-teacher', 'juf Nele', 'text'),
('klassen', 'klas-k1-text', 'In kleuterklas 1 maken de kinderen kennis met de schoolwereld. Spelen, ontdekken en samen leren staan centraal. Juf Nele begeleidt hen met veel geduld en warmte.', 'text'),
('klassen', 'klas-k1-photo', '', 'image'),
('klassen', 'klas-k1-tphoto', '', 'image'),
('klassen', 'klas-k1-blog', '/nl/klas-k1', 'text'),
('klassen', 'klas-k1-order', '-3', 'text'),
('klassen', 'klas-k2-name', 'Kleuterklas 2', 'text'),
('klassen', 'klas-k2-teacher', 'juf Anais', 'text'),
('klassen', 'klas-k2-text', 'In kleuterklas 2 gaan we verder met ontdekken en leren. De kinderen worden steeds zelfstandiger en maken kennis met letters en cijfers. Juf Anais zorgt voor een fijne leeromgeving.', 'text'),
('klassen', 'klas-k2-photo', '', 'image'),
('klassen', 'klas-k2-tphoto', '', 'image'),
('klassen', 'klas-k2-blog', '/nl/kleuterklas-2-juf-aurelie', 'text'),
('klassen', 'klas-k2-order', '-2', 'text'),
('klassen', 'klas-k3-name', 'Kleuterklas 3', 'text'),
('klassen', 'klas-k3-teacher', 'juf Evy', 'text'),
('klassen', 'klas-k3-text', 'De topperklas! Hier bereiden we de kinderen voor op het eerste leerjaar. Zelfstandigheid, schoolse vaardigheden en samenwerken staan centraal. Juf Evy maakt hen klaar voor de grote stap.', 'text'),
('klassen', 'klas-k3-photo', '', 'image'),
('klassen', 'klas-k3-tphoto', '', 'image'),
('klassen', 'klas-k3-blog', '/nl/kleuterklas-3-juf-evy', 'text'),
('klassen', 'klas-k3-order', '-1', 'text'),
('klassen', 'klas-1a-name', 'Klas 1A', 'text'),
('klassen', 'klas-1a-teacher', 'juf Lies / meester Simon', 'text'),
('klassen', 'klas-1a-text', 'Het eerste leerjaar! Een spannend jaar vol nieuwe ontdekkingen. Leren lezen, schrijven en rekenen.', 'text'),
('klassen', 'klas-1a-photo', '', 'image'),
('klassen', 'klas-1a-tphoto', '', 'image'),
('klassen', 'klas-1a-blog', '/nl/klas-1a', 'text'),
('klassen', 'klas-1a-order', '1', 'text'),
('klassen', 'klas-2a-name', 'Klas 2A', 'text'),
('klassen', 'klas-2a-teacher', 'juf Stefanie', 'text'),
('klassen', 'klas-2a-text', 'In het tweede leerjaar bouwen we verder op de basis. Lezen wordt vlotter, rekenen uitdagender.', 'text'),
('klassen', 'klas-2a-photo', '', 'image'),
('klassen', 'klas-2a-tphoto', '', 'image'),
('klassen', 'klas-2a-blog', '/nl/klas-2a', 'text'),
('klassen', 'klas-2a-order', '2', 'text'),
('klassen', 'klas-3a-name', 'Klas 3A', 'text'),
('klassen', 'klas-3a-teacher', 'juf Melissa', 'text'),
('klassen', 'klas-3a-text', 'Het derde leerjaar brengt nieuwe uitdagingen. Meer zelfstandig werken, complexere opdrachten en nieuwe vakken.', 'text'),
('klassen', 'klas-3a-photo', '', 'image'),
('klassen', 'klas-3a-tphoto', '', 'image'),
('klassen', 'klas-3a-blog', '', 'text'),
('klassen', 'klas-3a-order', '3', 'text'),
('klassen', 'klas-3b-name', 'Klas 3B', 'text'),
('klassen', 'klas-3b-teacher', 'juf Aurelie', 'text'),
('klassen', 'klas-3b-text', 'In klas 3B leren de kinderen steeds meer zelfstandig te werken. Projecten, groepswerk en nieuwe leerstof.', 'text'),
('klassen', 'klas-3b-photo', '', 'image'),
('klassen', 'klas-3b-tphoto', '', 'image'),
('klassen', 'klas-3b-blog', '', 'text'),
('klassen', 'klas-3b-order', '4', 'text'),
('klassen', 'klas-4a-name', 'Klas 4A', 'text'),
('klassen', 'klas-4a-teacher', 'juf Emma', 'text'),
('klassen', 'klas-4a-text', 'Het vierde leerjaar is een belangrijk jaar. De kinderen worden voorbereid op de bovenbouw.', 'text'),
('klassen', 'klas-4a-photo', '', 'image'),
('klassen', 'klas-4a-tphoto', '', 'image'),
('klassen', 'klas-4a-blog', '/nl/klas-4a', 'text'),
('klassen', 'klas-4a-order', '5', 'text'),
('klassen', 'klas-4b-name', 'Klas 4B', 'text'),
('klassen', 'klas-4b-teacher', 'juf Tine', 'text'),
('klassen', 'klas-4b-text', 'In klas 4B werken we aan zelfstandigheid en kritisch denken.', 'text'),
('klassen', 'klas-4b-photo', '', 'image'),
('klassen', 'klas-4b-tphoto', '', 'image'),
('klassen', 'klas-4b-blog', '', 'text'),
('klassen', 'klas-4b-order', '6', 'text'),
('klassen', 'klas-5a-name', 'Klas 5A', 'text'),
('klassen', 'klas-5a-teacher', 'juf Anneke', 'text'),
('klassen', 'klas-5a-text', 'Het vijfde leerjaar! Meer verantwoordelijkheid, uitdagende projecten en voorbereiding op het secundair.', 'text'),
('klassen', 'klas-5a-photo', '', 'image'),
('klassen', 'klas-5a-tphoto', '', 'image'),
('klassen', 'klas-5a-blog', '', 'text'),
('klassen', 'klas-5a-order', '7', 'text'),
('klassen', 'klas-6a-name', 'Klas 6A', 'text'),
('klassen', 'klas-6a-teacher', 'juf Kelly', 'text'),
('klassen', 'klas-6a-text', 'Het laatste jaar van de lagere school! Een bijzonder jaar vol mooie momenten en voorbereiding op het secundair onderwijs.', 'text'),
('klassen', 'klas-6a-photo', '', 'image'),
('klassen', 'klas-6a-tphoto', '', 'image'),
('klassen', 'klas-6a-blog', '', 'text'),
('klassen', 'klas-6a-order', '8', 'text'),
('klassen', 'klas-talen-name', 'Talenklas', 'text'),
('klassen', 'klas-talen-teacher', 'Talenklas team', 'text'),
('klassen', 'klas-talen-text', 'In onze talenklas krijgen kinderen extra ondersteuning in meertaligheid. We werken aan taaluitbreiding en taalverrijking.', 'text'),
('klassen', 'klas-talen-photo', '', 'image'),
('klassen', 'klas-talen-tphoto', '', 'image'),
('klassen', 'klas-talen-blog', '/nl/talenklas', 'text'),
('klassen', 'klas-talen-order', '9', 'text'),
('klassen', 'klas-sport-name', 'Sport', 'text'),
('klassen', 'klas-sport-teacher', 'Sportteam', 'text'),
('klassen', 'klas-sport-text', 'Beweging is belangrijk! In onze sportlessen leren kinderen niet alleen sportieve vaardigheden, maar ook samenwerken en plezier hebben in bewegen.', 'text'),
('klassen', 'klas-sport-photo', '', 'image'),
('klassen', 'klas-sport-tphoto', '', 'image'),
('klassen', 'klas-sport-blog', '/nl/sport', 'text'),
('klassen', 'klas-sport-order', '10', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- TEAM PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('team', 'hero-title', 'Ons Team', 'text'),
('team', 'hero-text', 'Maak kennis met ons team', 'text'),
('team', 'director-bio', '', 'text'),
('team', 'teachers-title', 'Leerkrachten', 'text'),
('team', 'teachers-subtitle', '', 'text'),
('team', 'lid-lid1-name', '', 'text'),
('team', 'lid-lid1-role', '', 'text'),
('team', 'lid-lid1-photo', '', 'image'),
('team', 'lid-lid1-bio', '', 'text'),
('team', 'lid-lid1-order', '1', 'text'),
('team', 'lid-lid2-name', '', 'text'),
('team', 'lid-lid2-role', '', 'text'),
('team', 'lid-lid2-photo', '', 'image'),
('team', 'lid-lid2-bio', '', 'text'),
('team', 'lid-lid2-order', '2', 'text'),
('team', 'lid-lid3-name', '', 'text'),
('team', 'lid-lid3-role', '', 'text'),
('team', 'lid-lid3-photo', '', 'image'),
('team', 'lid-lid3-bio', '', 'text'),
('team', 'lid-lid3-order', '3', 'text'),
('team', 'lid-lid4-name', '', 'text'),
('team', 'lid-lid4-role', '', 'text'),
('team', 'lid-lid4-photo', '', 'image'),
('team', 'lid-lid4-bio', '', 'text'),
('team', 'lid-lid4-order', '4', 'text'),
('team', 'lid-lid5-name', '', 'text'),
('team', 'lid-lid5-role', '', 'text'),
('team', 'lid-lid5-photo', '', 'image'),
('team', 'lid-lid5-bio', '', 'text'),
('team', 'lid-lid5-order', '5', 'text'),
('team', 'lid-lid6-name', '', 'text'),
('team', 'lid-lid6-role', '', 'text'),
('team', 'lid-lid6-photo', '', 'image'),
('team', 'lid-lid6-bio', '', 'text'),
('team', 'lid-lid6-order', '6', 'text'),
('team', 'support-title', 'Ondersteuning', 'text'),
('team', 'support-subtitle', '', 'text'),
('team', 'support-1-name', '', 'text'),
('team', 'support-1-bio', '', 'text'),
('team', 'support-2-name', '', 'text'),
('team', 'support-2-bio', '', 'text'),
('team', 'support-3-name', '', 'text'),
('team', 'support-3-bio', '', 'text'),
('team', 'cta-title', '', 'text'),
('team', 'cta-text', '', 'text'),
('team', 'contact-director-name', 'Inge Versavel', 'text'),
('team', 'contact-director-photo', '', 'image')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- OPVANG PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('opvang', 'hero-title', 'Voor- en Naschoolse Opvang', 'text'),
('opvang', 'hero-text', '', 'text'),
('opvang', 'schedule-title', 'Uurrooster', 'text'),
('opvang', 'schedule-subtitle', '', 'text'),
('opvang', 'morning-time', '7:00 - 8:15', 'text'),
('opvang', 'morning-text', '', 'text'),
('opvang', 'afternoon-time', '15:30 - 18:00', 'text'),
('opvang', 'afternoon-text', '', 'text'),
('opvang', 'activities-title', 'Activiteiten', 'text'),
('opvang', 'activities-subtitle', '', 'text'),
('opvang', 'activity-1-title', '', 'text'),
('opvang', 'activity-1-text', '', 'text'),
('opvang', 'activity-2-title', '', 'text'),
('opvang', 'activity-2-text', '', 'text'),
('opvang', 'activity-3-title', '', 'text'),
('opvang', 'activity-3-text', '', 'text'),
('opvang', 'activity-4-title', '', 'text'),
('opvang', 'activity-4-text', '', 'text'),
('opvang', 'activity-5-title', '', 'text'),
('opvang', 'activity-5-text', '', 'text'),
('opvang', 'activity-6-title', '', 'text'),
('opvang', 'activity-6-text', '', 'text'),
('opvang', 'practical-title', 'Praktisch', 'text'),
('opvang', 'price-1', '', 'text'),
('opvang', 'price-2', '', 'text'),
('opvang', 'price-3', '', 'text'),
('opvang', 'price-note', '', 'text'),
('opvang', 'register-1', '', 'text'),
('opvang', 'register-2', '', 'text'),
('opvang', 'register-3', '', 'text'),
('opvang', 'register-note', '', 'text'),
('opvang', 'team-title', 'Ons Opvangteam', 'text'),
('opvang', 'team-text', '', 'text'),
('opvang', 'sfeer-img-1', '', 'image'),
('opvang', 'sfeer-img-2', '', 'image'),
('opvang', 'cta-title', '', 'text'),
('opvang', 'cta-text', '', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- FOTOS PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('fotos', 'hero-title', 'Fotoalbum', 'text'),
('fotos', 'hero-text', '', 'text'),
('fotos', 'gallery-title', 'Sfeerbeelden', 'text'),
('fotos', 'gallery-subtitle', '', 'text'),
('fotos', 'gallery-1', '', 'image'),
('fotos', 'gallery-2', '', 'image'),
('fotos', 'gallery-3', '', 'image'),
('fotos', 'gallery-4', '', 'image'),
('fotos', 'gallery-5', '', 'image'),
('fotos', 'gallery-6', '', 'image'),
('fotos', 'gallery-7', '', 'image'),
('fotos', 'gallery-8', '', 'image'),
('fotos', 'gallery-9', '', 'image'),
('fotos', 'facebook-title', '', 'text'),
('fotos', 'facebook-text', '', 'text'),
('fotos', 'cta-title', '', 'text'),
('fotos', 'cta-text', '', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- PROJECTEN PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('projecten', 'hero-title', 'Projecten', 'text'),
('projecten', 'hero-text', '', 'text'),
('projecten', 'overview-title', '', 'text'),
('projecten', 'overview-subtitle', '', 'text'),
('projecten', 'timeline-title', '', 'text'),
('projecten', 'timeline-subtitle', '', 'text'),
('projecten', 'season-1-title', '', 'text'),
('projecten', 'season-1-period', '', 'text'),
('projecten', 'season-1-text', '', 'text'),
('projecten', 'season-2-title', '', 'text'),
('projecten', 'season-2-period', '', 'text'),
('projecten', 'season-2-text', '', 'text'),
('projecten', 'season-3-title', '', 'text'),
('projecten', 'season-3-period', '', 'text'),
('projecten', 'season-3-text', '', 'text'),
('projecten', 'season-4-title', '', 'text'),
('projecten', 'season-4-period', '', 'text'),
('projecten', 'season-4-text', '', 'text'),
('projecten', 'approach-title', '', 'text'),
('projecten', 'approach-text', '', 'text'),
('projecten', 'annual-title', '', 'text'),
('projecten', 'annual-subtitle', '', 'text'),
('projecten', 'annual-1-title', '', 'text'),
('projecten', 'annual-1-text', '', 'text'),
('projecten', 'annual-2-title', '', 'text'),
('projecten', 'annual-2-text', '', 'text'),
('projecten', 'annual-3-title', '', 'text'),
('projecten', 'annual-3-text', '', 'text'),
('projecten', 'annual-4-title', '', 'text'),
('projecten', 'annual-4-text', '', 'text'),
('projecten', 'annual-5-title', '', 'text'),
('projecten', 'annual-5-text', '', 'text'),
('projecten', 'annual-6-title', '', 'text'),
('projecten', 'annual-6-text', '', 'text'),
('projecten', '2021-poster', '', 'image'),
('projecten', '2022-poster', '', 'image'),
('projecten', '2023-poster', '', 'image'),
('projecten', '2024-poster', '', 'image'),
('projecten', 'cta-title', '', 'text'),
('projecten', 'cta-text', '', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;

-- =============================================
-- KALENDER PAGE
-- =============================================
INSERT INTO page_content (page_slug, content_key, content_value, content_type) VALUES
('kalender', 'live-title', '', 'text'),
('kalender', 'live-subtitle', '', 'text')
ON CONFLICT (page_slug, content_key) DO NOTHING;
